name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Hosted Windows Container
  steps:
  - checkout: self
  - task: Npm@1
    displayName: npm install
    inputs:
      workingDir: ui/helloworld
      verbose: false
  - task: Npm@1
    displayName: npm build
    inputs:
      command: custom
      workingDir: ui/helloworld
      verbose: false
      customCommand: run build -- --prod --configuration=tokenized --output-path=tokenized
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)\tokenizedapp'
    inputs:
      SourceFolder: $(system.defaultworkingdirectory)
      Contents: '**\tokenized\**'
      TargetFolder: $(build.artifactstagingdirectory)\tokenizedapp
      CleanTargetFolder: true
      OverWrite: true
      flattenFolders: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts: drop'
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)\tokenizedapp
      ArtifactName: tokenizedapp
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
...
